package com.flaviotps.provedor

// URLS
const val LOGIN_URL = "http://54.232.27.159:42069"
//EXTRA
const val EXTRA_KEY_LOGIN_RESPONSE = "LOGIN_RESPONSE"
const val EXTRA_KEY_HTML_RESPONSE = "EXTRA_KEY_HTML_RESPONSE"
//FRAGMENT TAGS
const val LOGIN_FRAGMENT_TAG = "LOGIN_FRAGMENT"
const val PLAN_FRAGMENT_TAG = "LOGIN_FRAGMENT"
const val HISTORIC_TICKET_FRAGMENT_TAG = "HISTORIC_TICKET_FRAGMENT_TAG"